# Generated by Django 3.1.5 on 2021-01-25 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='wait_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_finished_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 16, 38, 53, 961986)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_made_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 16, 39, 6, 150077)),
            preserve_default=False,
        ),
    ]
