# Generated by Django 3.1.5 on 2021-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_finished_date',
            field=models.DateField(null=True),
        ),
    ]
